version: '3.1'

services:

  postgres:
    image: postgres:alpine3.17
    container_name: tournament-db
    restart: always
    environment:
      POSTGRES_DB: tournament-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    networks:
      springboot-postgres-net:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '443:443'
    depends_on:
      - postgres
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tournament-db
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      springboot-postgres-net:

networks:
  springboot-postgres-net:
