version: '3.1'

services:

  postgres:
    image: postgres:alpine3.17
    container_name: tournament-db
    restart: always
    environment:
      POSTGRES_DB: tournament-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'